# NumPy
NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. Using NumPy, mathematical and logical operations on arrays can be performed. This tutorial explains the basics of NumPy such as its architecture and environment. It also discusses the various array functions, types of indexing, etc. An introduction to Matplotlib is also provided. All this is explained with the help of examples for better understanding.

In [2]:
import numpy as np 
a = 'hello world' 
print (a)

hello world


# NumPy - Ndarray Object
The most important object defined in NumPy is an N-dimensional array type called ndarray. It describes the collection of items of the same type. Items in the collection can be accessed using a zero-based index.

In [3]:
import numpy as np 
a = np.array([1,2,3]) 
print (a)

[1 2 3]


In [1]:
# more than one dimensions 
import numpy as np 
a = np.array([[1, 2], [3, 4]]) 
print (a)
a.dtype

[[1 2]
 [3 4]]


dtype('int32')

In [4]:
# minimum dimensions 
import numpy as np 
a = np.array([1, 2, 3,4,5], ndmin = 2) 
print (a)

[[1 2 3 4 5]]


In [6]:
# dtype parameter 
import numpy as np 
a = np.array([1, 2, 3], dtype = complex) 
print (a)

[ 1.+0.j  2.+0.j  3.+0.j]


# NumPy - Array Attributes

# ndarray.shape
This array attribute returns a tuple consisting of array dimensions. It can also be used to resize the array.

In [7]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
print (a.shape)

(2, 3)


In [17]:
# this resizes the ndarray 
import numpy as np 

a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (2,3) # 3 rows 2 columns
print (a) 

[[1 2 3]
 [4 5 6]]


# ndarray.ndim
This array attribute returns the number of array dimensions

In [9]:
# an array of evenly spaced numbers 
import numpy as np 
a = np.arange(24) 
print (a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [2]:
# this is one dimensional array 
import numpy as np 
a = np.arange(24)
print(a)
print(a.ndim) 

# now reshape it 
b = a.reshape(2,4,3) # 2 dimensions of 4 rows 3 columns
print (b) 
# b is having three dimensions

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


# NumPy - Array Creation Routines

In [1]:
import numpy as np 
x = np.empty([3,2], dtype = int) 
print (x)
# Note − The elements in an array show random values as they are not initialized.

[[4784215 4456526]
 [5701711 6029395]
 [7929939 7602291]]


# numpy.zeros
Returns a new array of specified size, filled with zeros.

In [8]:
# array of five zeros. Default dtype is float 
import numpy as np 
x = np.zeros(5) 
print (x)

[0. 0. 0. 0. 0.]


In [19]:
import numpy as np 
x = np.zeros((5), dtype = int) 
print (x)

[0 0 0 0 0]


# numpy.ones
Returns a new array of specified size and type, filled with ones.

In [10]:
# array of five ones. Default dtype is float 
import numpy as np 
x = np.ones(5) 
print (x)

[1. 1. 1. 1. 1.]


In [18]:
import numpy as np 
x = np.ones([2,2], dtype = int) 
print (x)

[[1 1]
 [1 1]]


# NumPy - Array From Existing Data

# numpy.asarray
This function is similar to numpy.array except for the fact that it has fewer parameters. This routine is useful for converting Python sequence into ndarray.

In [2]:
# convert list to ndarray 
import numpy as np 

x = [1,2,3] 
a = np.asarray(x) 
print (a)

[1 2 3]


In [8]:
# dtype is set 
import numpy as np 

x = [1,2,3]
a = np.asarray(x, dtype = float) 
print (a)

[1. 2. 3.]


In [10]:
# ndarray from tuple 
import numpy as np 

x = (1,2,3) 
a = np.array(x) 
print (a)

[1 2 3]


In [23]:
# ndarray from list of tuples 
import numpy as np 

x = [(1,2,3),(4,5)] 
a = np.asarray(x) 
print (a)

[(1, 2, 3) (4, 5)]


In [3]:
# create list object using range function 
import numpy as np 
list = range(5) 
a = np.array(list,dtype = float)
print(a)

[0. 1. 2. 3. 4.]


In [28]:
# obtain iterator object from list 
import numpy as np 
list = range(5) 
it = iter(list)  

# use iterator to create ndarray 
x = np.fromiter(it, dtype = float) 
print (x)

[ 0.  1.  2.  3.  4.]


# NumPy - Array From Numerical Ranges

In [29]:
import numpy as np 
x = np.arange(5) 
print (x)

[0 1 2 3 4]


In [30]:
import numpy as np 
# dtype set 
x = np.arange(5, dtype = float)
print (x)

[ 0.  1.  2.  3.  4.]


In [32]:
# start and stop parameters set 
import numpy as np 
x = np.arange(10,20,2) # start , stop , with gapmof 2
print (x)

[10 12 14 16 18]


# numpy.linspace
This function is similar to arange() function. In this function, instead of step size, the number of evenly spaced values between the interval is specified. The usage of this function is as follows −

In [6]:
import numpy as np 
x = np.linspace(10,20,5) # generate 5 elements , gaps decided itself
print (x)

[10.  12.5 15.  17.5 20. ]


In [10]:
# endpoint set to false 
import numpy as np 
x = np.linspace(10,20, 5, endpoint = False) 
print (x)

[10. 12. 14. 16. 18.]


In [3]:
# find retstep value 
import numpy as np 

x = np.linspace(1,2,5, retstep = True) 
print (x) 
# retstep here is 0.25

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)


# numpy.logspace
This function returns an ndarray object that contains the numbers that are evenly spaced on a log scale. Start and stop endpoints of the scale are indices of the base, usually 10.

In [13]:
import numpy as np 
# default base is 10 
a = np.logspace(1.0, 2.0, num = 10) # Start and stop endpoints of the scale are indices of the base, usually 10.
print (a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [38]:
# set base of log space to 2 
import numpy as np 
a = np.logspace(1,10,num = 10, base = 2) 
print (a)

[    2.     4.     8.    16.    32.    64.   128.   256.   512.  1024.]


# NumPy - Indexing & Slicing

In [40]:
import numpy as np 
a = np.arange(10) 
s = slice(2,7,2) #  start, stop, gapping
print (a[s])

[2 4 6]


In [42]:
import numpy as np 
a = np.arange(10) 
b = a[2:7:2]  #  start, stop, gapping
print (b)

[2 4 6]


In [1]:
# slice single item 
import numpy as np 

a = np.arange(10) 
b = a[5:9] 
print (b)

[5 6 7 8]


In [44]:
# slice items starting from index 
import numpy as np 
a = np.arange(10) 
print (a[2:])

[2 3 4 5 6 7 8 9]


In [45]:
# slice items between indexes 
import numpy as np 
a = np.arange(10) 
print (a[2:5])

[2 3 4]


In [47]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a)  

# slice items starting from index
print ('Now we will slice the array from the index a[1:]' )
print (a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]


In [5]:
# array to begin with 
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print ('Our array is:') 
print (a) 
print ('\n')  

# this returns array of items in the second column 
print ('The items in the second column are:')  
print (a[...,1]) 
print ('\n')  

# Now we will slice all items from the second row 
print ('The items in the second row are:')
print (a[1,...]) 
print ('\n')  

# Now we will slice all items from column 1 onwards 
print ('The items column 1 onwards are:') 
print (a[...,1:])

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


The items in the second column are:
[2 4 5]


The items in the second row are:
[3 4 5]


The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]


Functon        Description
abs,fabs      compute the absolute value element-wise for interger,floating,or complex values

sqrt          compute the square rootof each element(equivalent arr **0.5)

square        compute the square of each element.
exp           compute the exponent e* ofeach element
